"""create user library table

Revision ID: 038a16f31924
Revises: d6501b6e1945
Create Date: 2026-08-02 01:36:15.908111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038a16f31924'
down_revision: Union[str, Sequence[str], None] = 'd6501b6e1945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_library',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PLAN_TO_WATCH', 'WATCHING', 'COMPLETED', 'PAUSED', 'DROPPED', name='library_status', native_enum=False, create_constraint=True), server_default='PLAN_TO_WATCH', nullable=False),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_rating IS NULL OR (user_rating >= 0 AND user_rating <= 10)', name='ck_user_library_rating_range'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_user_library_user_media')
    )
    op.create_index('ix_user_library_user_status', 'user_library', ['user_id', 'status'], unique=False)
    op.create_index('ix_user_library_user_updated_at', 'user_library', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_library_user_updated_at', table_name='user_library')
    op.drop_index('ix_user_library_user_status', table_name='user_library')
    op.drop_table('user_library')
    # ### end Alembic commands ###
