"""add country code to users

Revision ID: c46bb14d88e5
Revises: aedc1d1b67d4
Create Date: 2026-07-29 20:41:23.024562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46bb14d88e5'
down_revision: Union[str, Sequence[str], None] = 'aedc1d1b67d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "country_code",
            sa.String(length=2),
            server_default="MX",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country_code')
    # ### end Alembic commands ###
